	window.accelon2017={
		corpora:["jushelunyaojie","songshujz07"],
		dictionaries:[
	{name:"一行",url:"http://buddhaspace.org/dict/index.php?keyword=$$"},
	{name:"萌典",url:"https://www.moedict.tw/$$"},
	{name:"康熙",url:"http://kangxi.adcs.org.tw/kangxizidian/#$$",max:1},
	{name:"百度",url:"http://www.baidu.com.cn/s?cl=3&wd=$$"}	
	],
	disableLayout:["yinshun","mpps"]
	}